name: e_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.8
  flutter:
    sdk: flutter
  
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/adidaslogo.png
    - assets/img1.png
    - assets/img2.png
    - assets/img3.png
    - assets/img4.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/adidaslogo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/adidaslogo.png"